//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18408
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class Cooldown
{
	public float Max { get; set; }
	float current;

	public Cooldown() {
		this.Max = 1.0f;
		this.current = 0;
	}
	
	public Cooldown(float max) {
		this.Max = max;
		this.current = 0;
	}

	public bool Armed {
		get { return current < 0; }
	}

	public void Active() {
		this.current = this.Max;
	}

	public void Tick() {
		this.current -= UnityEngine.Time.deltaTime;
	}

}

